---
title: "Assignment 2: Boulder County House Prices Algorithm"
author: "Gianluca Nelms and Alex Mangiapane"
date: "10/22/2021"
output:bookdown::gitbook:
    code_folding: hide
    fig_caption: yes
    toc: yes
editor_options: 
  markdown: 
    wrap: sentence
  #chunk_output_type: console
---

```{r setup, include=FALSE}
library(bookdown)
knitr::opts_chunk$set(
  echo=TRUE,
  include=TRUE,
  warning=FALSE,
  messages=FALSE,
  fig.width = 8,
  fig.keep = 'all',
  collapse=TRUE,
  cache=TRUE, 
  autodep=TRUE,
  root.dir = getwd()
  )

options(tigris_class = "sf")
```

# 0. Introduction

*What is the purpose of this project?*
*Why should we care about it?*
*What makes this a difficult exercise?*
*What is your overall modeling strategy?*
*Briefly summarize your results.*

Boulder County - population growing, Zillow wants us adjust their pricing algorithm to reflect now growing demand for houses.  

What are some aspects of Boulder County

```{r import_libraries, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen=999)

library(tidyverse)
library(lubridate)
library(RColorBrewer)
library(patchwork)
library(scales)
library(knitr)
library(kableExtra)
library(ggplot2)
library(caret)

library(tidycensus)
library(sf)
library(sp)
library(tmap)
#library(ggrepel)
library(tigris)
library(stargazer)
library(ggcorrplot)
library(glue)
library(rvest)
library(spatstat)
library(cowplot)
library(gridExtra)
library(ggpubr)
library(broom)

mile = 5280
sqmile = 27878000

str_replace_vector = function(string, replace, replacement='') 
  str_replace_all(string, setNames(rep(replacement, length(replace)), replace))

count_format = function(col) format(col, digits=0, big.mark = ",")
proportion_format = function(col, digits=2) (col*100) %>%
      round(., digits=digits) %>% paste(., '%',sep='')


count_unique = function(raw_vector) print(c(length(raw_vector), length(unique(raw_vector))))

ceiling_n = function(num, by=10) ceiling(num/by) * by
ceiling_10 = function(num) ceiling_n(num, by=10)
ceiling_5 = function(num) ceiling_n(num, by=5)

mapTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 16,colour = "black"),
    plot.subtitle=element_text(face="italic"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.text.x = element_text(size = 14))
}

plotTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 16,colour = "black"),
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.1),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=12),
    
    axis.title = element_text(size=12),
    axis.text = element_text(size=10),
    
    
    plot.background = element_blank(),
    
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "italic"),
    legend.text = element_text(colour = "black", face = "italic"),
    
    strip.text.x = element_text(size = 14)
  )
}




sf_to_labels = function(
  sf_focus, label_field
){
  sf.focus.labels = 
    sf_focus %>%
    st_centroid(., of_largest_polygon = TRUE) %>% 
    mutate(
      lon = map_dbl(geometry, 
                    ~st_centroid(.x, of_largest_polygon = TRUE, quiet = TRUE,)[[1]]),
      lat = map_dbl(geometry, 
                    ~st_centroid(.x, of_largest_polygon = TRUE, quiet = TRUE,)[[2]])
    )
  
  sf.focus.labels$label = sf.focus.labels[[label_field]]
  
  #     ,
  #     size = 
  #           ifelse(grepl('city', name_long), 2,
  #                  ifelse(grepl('town', name_long), 1.5,
  #                         ifelse(grepl('CDP', name_long), 0,
  #                                0)))) %>% 
  # filter(size>0)

  return(sf.focus.labels %>% select(label, lon, lat))
}

get_labels = function(
  cut_breaks, round_digit = 0, bucket_diff=1, first_start_range=0, last_end_range=TRUE, input_end_range='', bucket_suffix='', bucket_prefix=''
){
  labels = 
    cut_breaks %>% gsub(",", " to ", .) %>% 
    str_sub(., 2, -2) %>% unique(.)
  
  list_str = function(l, remove=0){
      format(round(as.numeric(l), digit=round_digit)-remove, big.mark=",")}
  
  for (i in seq(from=1,to=length(labels))){
    bucket_range = labels[i] %>% str_split(., " to ")
    
    start_range = paste(bucket_prefix, list_str(bucket_range[[1]][1]))
    end_range = paste(list_str(bucket_range[[1]][2], remove=bucket_diff), bucket_suffix)
    
    if (i == 1 & first_start_range != ''){
      start_range = paste(bucket_prefix, list_str(first_start_range))}
    if (i == length(labels) & input_end_range!=''){
      end_range=paste(list_str(input_end_range), bucket_suffix)
      last_end_range=TRUE
      }
    if (i == length(labels) & last_end_range==FALSE){end_range='+'}
    
    bucket = paste(
        start_range, 
        'to', 
        end_range) %>% str_trim()
    labels[i] = bucket}
    
  return(labels)
  }

geom_text_sf = function(
  sf.focus.labels,
  fontface='bold', color='black', label.size = 0.25,
  size = 3, check_overlap = TRUE
){
  labels = 
    geom_text(
        data=sf.focus.labels, check_overlap=TRUE,
        fontface=fontface, color=color,
        aes(x=lon,y=lat, label=label))
  return(labels)}


mutate_by <- function(.data, group, ...) {

  group_by(.data, !!enquo(group)) %>%
    mutate(...) %>%
    ungroup()

}

plot_limits = function(
  data = '',
  # buffer between plot's limits and the geometry 
  # (in unit of geometry column)
  buffer = 0
){
  # creates bounding box
  poly.bbox =
    data %>% st_union() %>%
    # buffers the geometry so the ultimate plot has margins
    st_buffer(buffer) %>%
    st_bbox()
  return(
    # returns the 'coord_sf' function which you can add to any plot
    coord_sf(
      xlim = c(poly.bbox['xmin'], poly.bbox['xmax']),
      ylim = c(poly.bbox['ymin'], poly.bbox['ymax']),
      crs = st_crs(data)
  ))}

```
