---
title: "Assignment 2: Boulder County House Prices Algorithm"
author: "Gianluca Nelms and Alex Mangiapane"
date: "10/22/2021"
output:bookdown::gitbook:
    code_folding: hide
    fig_caption: yes
    toc: yes
editor_options: 
  markdown: 
    wrap: sentence
  chunk_output_type: console
---
#bookdown::render_book('index.Rmd', 'bookdown::gitbook')

```{r setup, include=FALSE}
library(bookdown)
knitr::opts_chunk$set(
  echo=TRUE,
  include=TRUE,
  warning=FALSE,
  messages=FALSE,
  fig.width = 8,
  fig.keep = 'all',
  collapse=TRUE,
  cache=TRUE, 
  autodep=TRUE,
  root.dir = getwd()
  )

options(tigris_class = "sf")
```

# 0. Introduction

```{r child = '00-intro.Rmd'}
```

-------------------------------

# 1. Data
*creates Boulder.data, predict.0, predict.1*
```{r child = '01-data.Rmd'}
```

-------------------------------
# 2.	EDA
*tables, plots, means*
```{r child = '02-EDA.Rmd'}
```

-------------------------------

# 3.	Linear Results 
*create lm train, cv test*
*plot, tabls*
```{r child = '03-results.Rmd'}
```
----------------------------------

# 4.	Spatial Results 

```{r child = '04-spatial.Rmd'}
```
----------------------------------

```{r render}
rmarkdown::render('index.Rmd')
```
